  
# This is a basic workflow to help you get started with Actions


name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install NodeJS
      uses: actions/setup-node@v2.1.2
      
    - name: Install Yarn
      run: sudo npm install -g yarn
        
    - name: Install related libraries
      run: |
        sudo yarn add react-redux @reduxjs/toolkit @types/react-redux @material-ui/core
        sudo yarn add history@5 react-router-dom@6.0.0-beta.0 @types/react-router-dom @material-ui/icons
      
    - name: Install surge
      run: sudo yarn global add surge
                  
    - name: Build React App
      run: yarn build
      
    - name: Deploy surge
      run: surge ./build store_app.surge.sh --token ${{secrets.SURGE_TOKEN}}
